apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-group-18-fastfood-backend
data:
  POSTGRES_DB: "root"
  POSTGRES_HOST: "postgres"
  MONGO_INITDB_DATABASE: "food-fusion-order"
  MONGO_INITDB_HOST: "mongodb-food-fusion-service"